### PR TITLE
Flow navigation logic and a single-activity app sample

### PR DESCRIPTION
**Pull request by Terenfear**
I was experimenting with single-activity apps and decided to try to implement reusable flows logic.  Basically it's similar to the existing screen switching logic, but it has more navigation commands and allows you to return results to another naviagation stacks. My implementation works only with nested fragments, but I think it's possible to implement it with activities.
All new commands are very similar to the existing ones but operate only with "flow" screens to avoid clashing with regular activities and fragments that don't host another screens inside. All corresponding navigator methods have the same parameters as their regular counterparts.
So, the list is (new command - regular analogue):
1. addFlow - goForward
2. replaceFlow - replace
3. resetFlow - reset
4. finishFlow - finish
5. backToFlow - backTo
6. back - updated an existing version, now it checks for existing flow fragments in a top-level fragment manager using FragmentFlowManager

Finish and backTo also have "with result" variants. All new commands delegate activity/fragment creation logic to an implementation of FlowManager class, kind of like SwitchToCommand does with implementations of ScreenSwitcher class.

The sample is very simple and just shows a basic behavior of single-activity navigation as well as some usages of navigation flows.

### CODE REVIEW

**Comment by aartikov** [comment]
@Terenfear 
Wow! You have done a great job! Thank you. The pull request looks good. I will merge it. Support of single activity approach is a must-have feature for a navigation library according to the latest trends. 
But there are some investigations I want to do before the release.

1) Maybe it will be better to proclaim flow screens on a declaration side but not on a call side. In other words instead of new methods `addFlow`, `replaceFlow` etc. we can add interface `FlowScreen` to mark required screens. It will simplify `Navigator` interface. Only one new method `finishFlow` will be required.

2) I don’t like the name of `finish` method now. `finishFlow` is okay, but just `finish`. What does it mean? It can be called `finishApplication` for a single activity app, but I want to support a mixed navigation too.

3) There are two `TransitionListener`s now. I think we can make one listener, but change the interface to distinguish between usual fragments and flow fragments.

4) I like how most of the flow navigation code is taken out from the commands to `FlowManager`. I want to do the same thing for other commands and reduce duplication between flow navigation and usual fragment navigation.

5) The configuration of `NavigationContext` looks a little bit tricky for single activity navigation. Maybe it can be simpler.

6) Your sample looks good. But I think we can just copy “navigation methods sample” and redo it to single activity approach. It will show how navigation methods work in different combinations.

**Comment by Terenfear** [comment]
Hey, thanks for the feedback, really appreciate it! The things you mentioned are quite interesting and I'd be glad to discuss the details. In advance I want to apologize for my awkward English.

1. I've thought about making a separate interface for flows, but after some thinking I've decided against it. The main reason is the ability to use any screen with and without flows. This way a developer has more ways to reuse a screen while having a clear way to understand what will happen to the navigation stack after each method call. I agree that it's a questionable decision which makes the lib's API more complex in order to provide more "freedom" and it's not excellent. Oh, and, correct me if I'm mistaken, addition of the `FlowScreen` class will make the inner logic a bit trickier as it would lead to addition of at least two new screen implementations: `FragmentFlowScreenImplementation` and `ActivityFlowScreenImplementation`.
2. I agree that now `finish` sounds a bit disorienting, so maybe it could be rebranded as something like `finishGroup`. To be honest I don't like the idea of adding the "group" concept to the terminology, bit it's a tough problem. I mean, if we decouple screens and the navigation itself from the Android view components such as activities and fragments, then we're left with a conundrum. For now `finish` operates only on `Activity`, which, as you mentioned, serves more like an "application" for single-activity apps and at the same time as a normal screen or a group container for traditional apps. So the command should somehow include both of these meanings and be distinguishable from `finishFlow`. I can't find a better solution than `finishGroup`, even though I'm not content with it.
3. If you decide that the `FlowScreen` idea is the right way to go, than we can easliy use one `TransitionListener` and developers will be able to distingish between screen transitions and flow transitions by checking assignability of `screenFrom\screenTo` classes to `FlowScreen`. Maybe it's better to add another parameter to `onScreenTransition` method, but I think it has enough parameters already and it makes me kind of uncomfortable. Oh, also I guess it's alright to just add another method (`onFlowTransition`) into `TransitionListener` class with the same parameters. Yeah, it will force everybody to implement both of the methods even for traditional apps without these navigation flows, but it can be solved extending an empty public default implementation of the interface, so not a big deal.
4. I like the idea of getting rid of duplicate code, maybe it can be done using specific separate helper classes for fragments and activities. Similar to `FragmentStack` class, but with with the higher level logic and stored as singletones inside a navigator. As I see it, these classes would be injected into the current `NavigationContext` by `NavigationContextBinder` during the first binding and then used inside the context by simple command implementations and `FlowManager`. Custom implementations of these classes could be provided as constructor parameters of `AndroidNavigator`. Meh, not the prettiest concept, I know, but IMHO it's should do the job and it's simple enough
5. I've tried to mimic the configuration of an activity with `ScreenSwitcher` to make it more comfortable for the ones who has used Alligator before. It looks more or less fine to me, and it will be simpler if we get rid of the second transition listener. Still I'm a bit uncomfortable with the result handling logic. What things do you personally find the trickiest?
6. I agree. I've commited the sample I used myself during experiments just as a simple way to present the implementation. A rewritten copy of the existing sample will fit better, no doubts. I guess it won't be difficult to do once the aforementioned things are resolved.

**Comment by aartikov** [comment]
1. It is hard for me to imagine a use case where the same fragment can be used as a normal screen and as a flow screen. Usually a normal screen has some UI where as flow screen has just a container for other fragments.
I suggest to add `FlowScreen` interface that extends `Screen`. The fact that some screen implements this interface will be enough for Alligator to understand that it executes flow command. Users of the library can use some naming convention (for example add prefix `Flow` to flow screens) for addition clarifying. 
I don't see reasons to add another screen implementation. Flow screens can be implemented with `FragmentScreenImplementation`.

2. Yeah, naming is hard. Let's leave this question opened.

3. I suggest this `TransitionListener`:
```void onScreenTransition(TransitionType transitionType, ScreenType screenType, Class<? extends Screen> screenClassFrom, Class<? extends Screen> screenClassTo)```
Where `ScreenType` is enum: `ACTIVITY`, `FRAGMENT`, `FLOW_FRAGMENT`.
The same for `TransitionAnimationProvider`.

4. I think to call this high level classes navigators. There will be `ActivityNavigator`, `FragmentNavigator`, `DialogFragmentNavigator`. Navigators operate with screen implementations. `NavigationContext` creates navigators during configuration and provides them to commands. A command resolves screen implementations and calls a required navigator. There will be two instances of `FragmentNavigator`: first for normal fragments and the second for flow fragments. So fragment navigator will take a function of flow manager. I don’t make plans about flow navigation based on activities. Maybe there is no point to implement it at all.

5. The same things that are tricky in advanced screen switcher sample. You need to rebind navigation context in the right moments. You need to get a container id for nested fragments. You need to handle a screen result in fragments somehow. Maybe it can be simpler.
I try to make Alligator as a library not as a framework. That is why there are no base classes like NavigationActivity or NavigationFragment. But this approach requires some plumbing code to make things work.

**Comment by Terenfear** [comment]
1\. Fragment could be used as a normal fragment and as a flow fragment in cases where a screen, implemented by this fragment, sometimes has to host an optional complex UI element with pseudo-navigation logic (some built-in quiz form, for example). But maybe I'm just overcomplicating things now, same things could be done using a viewpager in a usual non-flow fragment. So yeah, guess you're right.

3\. Looks pretty good. Although, while we're at it, maybe it's worth to add the fourth `TranstionType` - `DIALOG_FRAGMENT`?

4\. I like the idea of high level navigators. And yeah, flow navigation based entirely on activities is a strange thing, I agree, but still someone might try to implement it using a custom `FlowManager` and altered commands. I don't know, maybe marking a start of a new activity flow with some "checkpoint", putting it in a stack and then popping it with something like `backTo(LAST_CHECKPOINT)` command. Ah well, if someone would really decide to do that, it could be implemented without `FlowManager` as well. So I agree, it's better to add high level navigators and replace `FlowManager` with a distinct `FragmentNavigator`.

5\. It is a bit complicated, yeah, but from my experience most of this logic is written only once for some base activity and fragment classes, so I never really bothered with it.

**Comment by aartikov** [comment]
> Although, while we're at it, maybe it's worth to add the fourth ScreenType - DIALOG_FRAGMENT?

For dialogs separate interfaces are used: `DialogShowingListener` and `DialogAnimationProvider`.

**Comment by aartikov** [comment]
@Terenfear I have implemented discussed ideas here https://github.com/aartikov/Alligator/tree/feature/flow-navigation

**Comment by Terenfear** [comment]
I've looked through most of the changes and played with the new sample, it all looks really good. Although I don't understand how to finish a flow now. I've run my old sample with the new flow navigation logic and it all worked great until I tried to finish the second flow and return to the first one with a result. If I'm not mistaken, finishing flow would be implemented using `goBack` method of `FragmentNavigator`, but right now it's used only inside `BackCommand`. Is it all related to the ambiguous naming problem we've discussed earlier or am I just missing something?

**Comment by aartikov** [comment]
Oh, it had not been implemented yet when you viewed. I have pushed a new commit.
It is my attempt to make `finish` command more universal. Now this command finishes a current flow fragment if it exists or a current activity otherwise. In other words it finishes a flow (in a broad sense) regardless of which approach is used: single activity or activity per flow. 
I have also added `finishTopLevel` method which always finishes an activity. I am not sure that it is useful. Just added it for completeness.
What do you think?

**Comment by Terenfear** [comment]
Ah, got it. I like the idea of making `finish` more universal, it's quite simple, intuitive and doesn't break existing old projects. `finishTopLevel` might come in handy in some tricky cases when we have to gracefully close a single-activity app, so I think it's useful. I've run my experiments, everyrthing works pretty good. 
It seems a migration from the prevoius major version would only require small changes to context rebinding and listeners' implementations, which is fine. 
The only thing that puzzles me a bit is result handling in flow-to-flow navigation. I might be wrong, but right now it can be done only using a result listener from an activity, which delegates handling to the current flow fragment. It would be easier to directly use a listener from the destination flow (if it has one), but it seems impossible. Flow transition always leads to creation of a new navigation context. Listeners are set during a rebinding process, but the flow fragment navigator operates with listeners set during the last rebinding, which doesn't let us to use a result listener from the newly binded context. In the meantime activities have `ActivityResultHandler` to resolve a similar issue. So, what do you think, is it worth it to implement something like `FragmentResultHandler` that would pass a result to the new navigation context, or is it fine as it is?

**Comment by aartikov** [comment]
@Terenfear, thank you for the feedback.
Yes, now a screen result listener can only be set with `NavigationContext` and it is recommended to bind `NavigationContext` in an activity. I hope it is not too tedious for users of the library to propagate screen results to flow fragments, usual fragments, presenters and so on.

I don't understand how you suggest to set a screen result listener directly from fragments. Could you clarify please? In `DefaultFragmentNavigator` the line `mScreenResultHelper.callScreenResultListener(...)` goes after `callTransitionListener(...)`. Is it a problem?

**Comment by Terenfear** [comment]
Excuse me, I'm not good when it comes to describng these kinds of things in English. I was talking about which reuslt listener to use when the navigation context is rebinded in an activity. We can use some result listener declared in the activity or we can try to get the result listener of the current flow fragment, which implements, for example, some `ResultListenerProvider` interface. Kind of like we do to get a `containerId` from a flow fragment. In my opinion using flow fragment's result listener is a bit more intuitive than using activity's result listener which propagates results to the current flow fragment. 

So, lets imagine I have two flow fragments: A and B, each one has its own result listener and implements some `ResultListenerProvider`, meaning the fragments can provide their result listeners to whomever needs it. Activity uses these fragments' result listeners when it builds a navigation context.  I have the flow A in the backstack and now I'm on the flow B. The current navigation context has a result listner provided by the current flow - flow B. I want to finish the current flow with some result, which should be processed in the previous flow (flow A). I invoke `finishWithResult`, it pops the current flow fragment and calls a transition listener, decalred in the activity. This transition has `FLOW_FRAGMENT` destination type, so the activity starts to build a new navigation context. _Activity gets the current flow fragment (now that's the flow A), gets its result listener and uses this listener to build the new navigation context._ Navigation command is almost processed, all that's left is to pass a result from the flow B to a result listener. And there's the problem. The command's logic doesn't know that there's the new naviagion context with the new result listener. Command was invoked in the previous navigation context which had the result listener of the flow B, so it calls this listener and the result goes to the flow B instead of the intentioned flow A.

**Comment by aartikov** [comment]
Ok, I got it. You are right. It is impossible to set another screen result listener for an already executing command. I don't see an easy way to change this behavior and suppose it is better not to change it. What is really required is a better documentation for result handling, screen switchers, flows and so on.

**Comment by aartikov** [comment]
I plan to release this feature at the beginning of September.

**Comment by Terenfear** [comment]
Well, I've been a little enthusiastic and I've decided to use the current snapshot of the flow navigation branch for my project, considering it works great. So far so good, but still I appreciate the notice, I'll switch to the next major release when you think it's ready.

**Comment by aartikov** [comment]
@Terenfear Alligator 4.0.0 is released! Sorry for the delay.

**Comment by Terenfear** [comment]
Awesome, thanks for the update!

**Pull request merged**
